SET DEFINE OFF;
Insert into MONEDA
   (ID, ID_PAIS, MONEDA)
 Values
   (1, 1, 'Pesos mexicanos');
Insert into MONEDA
   (ID, ID_PAIS, MONEDA)
 Values
   (2, 1, 'Dolares');
Insert into MONEDA
   (ID, ID_PAIS, MONEDA)
 Values
   (3, 2, 'Pesos Argentinos');
Insert into MONEDA
   (ID, ID_PAIS, MONEDA)
 Values
   (4, 2, 'Dolares');
Insert into MONEDA
   (ID, ID_PAIS, MONEDA)
 Values
   (5, 3, 'Dolares');
COMMIT;
