CREATE TABLE DATOS_PROVEEDOR_PREGUNTAS (
  ID           NUMBER(10)    NOT NULL,
  FOLIO_PROVE   VARCHAR(20),
  ORIGEN_CTA    CHAR(2 BYTE),
  ID_PAIS       INTEGER,
  ID_MONEDA     INTEGER,
  PERSONALIDAD  CHAR(2 BYTE)
  );

ALTER TABLE DATOS_PROVEEDOR_PREGUNTAS ADD (
  CONSTRAINT pro_pk_3 PRIMARY KEY (ID));

CREATE SEQUENCE dept_seq_p_3;

CREATE OR REPLACE TRIGGER dept_bir_p_3
BEFORE INSERT ON DATOS_PROVEEDOR_PREGUNTAS
FOR EACH ROW

BEGIN
  SELECT dept_seq_p_3.NEXTVAL
  INTO   :new.id
  FROM   dual;
END;